<template>
  <view class="rgc">
    <view class="rgc__header"><text class="rgc__brand">RehabMotion</text><text class="rgc__title">康复游戏中心</text><text class="rgc__sub">选择训练游戏，运动数据与游戏奖励分别记录</text></view>
    <view class="rgc__games">
      <view class="rgc__card" @click="open('/pages-fruit-game/home/index')"><view class="rgc__cover rgc__cover--fruit"><text>🍎</text><i/><i/><i/></view><view class="rgc__body"><text>摘水果</text><small>肘关节屈伸 · 单人 / 多人</small><button>进入游戏</button></view></view>
      <view class="rgc__card rgc__card--penalty" @click="open('/pages-penalty-game/home/index')"><view class="rgc__cover rgc__cover--penalty"><text>⚽</text><i/><i/><i/></view><view class="rgc__body"><text>点球大战</text><small>膝关节屈伸 · 单人 / 多人</small><button>进入游戏</button></view></view>
      <view class="rgc__card rgc__card--vitality" @click="open('/pages-vitality-park/home/index')"><view class="rgc__cover rgc__cover--vitality"><text>🌳</text><i/><i/><i/></view><view class="rgc__body"><text>活力公园</text><small>坐到站 · 单人训练</small><button>进入游戏</button></view></view>
      <view class="rgc__card rgc__card--mole" @click="open('/pages-mole-game/home/index')"><view class="rgc__cover rgc__cover--mole"><text>🐹</text><i/><i/><i/></view><view class="rgc__body"><text>地鼠大作战</text><small>箱式深蹲 · 单人 / 2–5人PK与合作</small><button>进入游戏</button></view></view>
    </view>
  </view>
</template>
<script lang="ts">import{resolveDebugEnabled}from'../../game-platform/runtime/debug-gate';export default{name:'RehabGameCenter',data(){return{navigating:false,debugEnabled:false}},onLoad(query:Record<string,string|undefined>){this.debugEnabled=resolveDebugEnabled(query?.debug)},onShow(){this.navigating=false},methods:{open(url:string){if(this.navigating)return;this.navigating=true;uni.navigateTo({url:`${url}${this.debugEnabled?'?debug=1':''}`,fail:()=>{this.navigating=false}})}}}</script>
<style scoped>.rgc{box-sizing:border-box;min-height:100vh;padding:calc(env(safe-area-inset-top) + 34px) 18px 36px;background:linear-gradient(145deg,#eaf8e2,#e2f3ff 55%,#fff5ca);font-family:"Microsoft YaHei",sans-serif;color:#24523b}.rgc__header{width:min(880px,94vw);margin:auto}.rgc__brand,.rgc__title,.rgc__sub,.rgc__body text,.rgc__body small{display:block}.rgc__brand{color:#248447;font-weight:900}.rgc__title{font-size:clamp(34px,8vw,54px);font-weight:900}.rgc__sub{color:#6f8275}.rgc__games{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;width:min(880px,94vw);margin:24px auto 0}.rgc__card{overflow:hidden;border:3px solid #67a83d;border-radius:24px;background:#fff;box-shadow:0 9px 0 rgba(56,104,36,.2)}.rgc__card--penalty{border-color:#2c8ccc;box-shadow:0 9px 0 rgba(25,91,134,.2)}.rgc__card--mole{border-color:#a4722f;box-shadow:0 9px 0 rgba(120,77,28,.2)}.rgc__cover{position:relative;display:flex;align-items:center;justify-content:center;height:190px;overflow:hidden;background:linear-gradient(#54c9f2 0 52%,#91d646 52%)}.rgc__cover--penalty{background:linear-gradient(#42b8ed 0 48%,#49aa3e 48%)}.rgc__cover--mole{background:linear-gradient(#77c9ec 0 45%,#8dcd46 45%)}.rgc__cover>text{position:relative;z-index:2;font-size:76px}.rgc__cover i{position:absolute;bottom:20px;width:90%;height:5px;border-radius:50%;background:rgba(255,255,255,.8)}.rgc__cover i:nth-child(2){bottom:46px;width:55%}.rgc__cover i:nth-child(3){bottom:auto;top:30px;right:20px;width:80px;height:34px;background:rgba(255,255,255,.7)}.rgc__body{padding:18px}.rgc__body>text{font-size:29px;font-weight:900}.rgc__body small{margin-top:4px;color:#718079}.rgc__body button{display:flex;align-items:center;justify-content:center;width:100%;height:48px;margin:16px 0 0;padding:0;border:0;border-radius:999px;background:#61bd29;color:#fff;font-size:17px;font-weight:900}.rgc__card--penalty button{background:#2e98d9}.rgc__card--mole button{background:#a97936}@media(max-width:650px){.rgc__games{grid-template-columns:1fr}.rgc__cover{height:155px}}@media(orientation:landscape) and (max-height:480px){.rgc{padding-top:14px}.rgc__games{margin-top:12px}.rgc__cover{height:115px}.rgc__body{padding:10px}.rgc__body button{height:40px;margin-top:8px}}</style>
