<template><view class="vp-prepare" :style="viewportCss"><view class="vp-prepare__card"><button class="vp-prepare__back" @click="back">← 返回</button><text class="vp-prepare__eyebrow">坐到站康复训练</text><text class="vp-prepare__title">活力公园</text><view class="vp-prepare__params"><text>目标次数：{{ config.targetCount }} 次</text><text>训练组数：{{ config.targetSets }} 组</text><text>有效角度：{{ config.validAngleDeg }}° · 回位：{{ config.returnAngleDeg }}°</text></view><text class="vp-prepare__guide">请坐稳，双脚踩地，保持身体自然。开始前请保持坐姿不动。</text><view class="vp-prepare__count">{{ countdown>0?countdown:'准备完成' }}</view><button class="vp-prepare__start" :disabled="countdown>0" @click="start">{{ countdown>0?'请保持坐姿':'进入训练' }}</button></view></view></template>
<script lang="ts">
import { appendReturnUrl, configureCallerReturnUrl, getCallerReturnUrl, returnToCaller } from '../../game-platform/runtime/navigation'
import { resolveDebugEnabled } from '../../game-platform/runtime/debug-gate'
import { getViewportLayout, viewportStyle } from '../../game-platform/runtime/viewport'
import { configureVitalitySession, getVitalityConfig, registerVitalityResultEmitter } from '../runtime/session-runtime'
export default {name:'VitalityParkPrepare',data(){return{config:getVitalityConfig(),countdown:3,timer:null as ReturnType<typeof setInterval>|null,started:false,viewport:getViewportLayout()}},computed:{viewportCss():Record<string,string>{return viewportStyle(this.viewport,'--vp-safe-top')}},onLoad(query:Record<string,string|undefined>){configureCallerReturnUrl(query?.returnUrl,'/pages-vitality-park/home/index');const params:Record<string,number>={};(['targetCount','targetSets','frameRateHz','targetAngleDeg','validAngleDeg','returnAngleDeg'] as const).forEach((key)=>{if(query?.[key]!==undefined)params[key]=Number(query[key])});this.config=configureVitalitySession({...params,debugEnabled:resolveDebugEnabled(query?.debug)});try{const channel=(this as any).getOpenerEventChannel?.();registerVitalityResultEmitter((result)=>channel?.emit('vitalityParkResult',result))}catch{registerVitalityResultEmitter(null)}this.timer=setInterval(()=>{if(this.countdown>0)this.countdown-=1;else this.clearTimer()},1000)},onResize(){this.viewport=getViewportLayout()},onUnload(){this.clearTimer()},onBackPress(){this.back();return true},methods:{clearTimer(){if(this.timer)clearInterval(this.timer);this.timer=null},start(){if(this.countdown>0||this.started)return;this.started=true;this.clearTimer();uni.redirectTo({url:appendReturnUrl('/pages-vitality-park/game/index')})},back(){this.clearTimer();registerVitalityResultEmitter(null);returnToCaller({returnUrl:getCallerReturnUrl()})}}}
</script>
<style scoped>
.vp-prepare{box-sizing:border-box;display:flex;align-items:center;justify-content:center;width:100vw;height:100vh;min-height:260px;padding:calc(var(--vp-safe-top,8px) + 4px) 12px 10px;background:linear-gradient(145deg,#dff6dc,#fff4c5);font-family:"Microsoft YaHei",sans-serif;color:#315c37}.vp-prepare__card{width:min(720px,94vw);box-sizing:border-box;padding:18px 24px;border:3px solid #70ae52;border-radius:22px;background:#fff;box-shadow:0 8px 0 rgba(52,105,42,.16)}.vp-prepare__back{display:flex;align-items:center;justify-content:center;width:110px;height:36px;margin:0 0 6px;padding:0;border:0;border-radius:999px;background:#eaf6e6;color:#39733b}.vp-prepare__eyebrow,.vp-prepare__title,.vp-prepare__guide{display:block}.vp-prepare__eyebrow{font-weight:800}.vp-prepare__title{color:#2d823b;font-size:38px;font-weight:900}.vp-prepare__params{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.vp-prepare__params text{padding:7px 10px;border-radius:10px;background:#f0f9ea;color:#557151;font-size:13px}.vp-prepare__guide{color:#687b64;font-size:14px}.vp-prepare__count{margin:10px 0;text-align:center;color:#4b9b43;font-size:30px;font-weight:900}.vp-prepare__start{display:flex;align-items:center;justify-content:center;width:220px;height:46px;margin:auto;border:0;border-radius:999px;background:#58b62d;color:#fff;font-size:17px;font-weight:900}.vp-prepare__start[disabled]{background:#aac89f}
</style>
