import { createInitialSquatFrame,type SquatMotionFrame } from '../types/motion'
import type { MoleControllableDataSource } from './contracts'
export interface MoleFakeOptions{targetCount?:number;targetSets?:number;frameRateHz?:number;targetAngleDeg?:number;validAngleDeg?:number;returnAngleDeg?:number;restDurationSec?:number}
export class MoleFakeDataSource implements MoleControllableDataSource{
 private listeners=new Set<(f:SquatMotionFrame)=>void>();private timer:ReturnType<typeof setInterval>|null=null;private auto:ReturnType<typeof setInterval>|null=null;private frame:SquatMotionFrame;private dir:'down'|'up'|'none'='none';private intervalMs:number;private restDurationSec:number;private startedAt=0;private restAt=0;private armed=false;private extrema={min:0,max:0};private after:'REST'|'FINISHED'|null=null
 constructor(o:MoleFakeOptions={}){this.frame=createInitialSquatFrame(Math.max(1,Math.round(o.targetCount??10)),Math.max(1,Math.round(o.targetSets??3)));this.intervalMs=Math.round(1000/Math.min(50,Math.max(5,o.frameRateHz??25)));this.restDurationSec=Math.max(0,Math.round(o.restDurationSec??30));this.frame.target_angle_deg=o.targetAngleDeg??90;this.frame.valid_angle_deg=o.validAngleDeg??70;this.frame.return_angle_deg=o.returnAngleDeg??20}
 start(){if(!this.timer){if(!this.startedAt)this.startedAt=Date.now();this.timer=setInterval(()=>this.tick(),this.intervalMs);this.tick()}}
 stop(){if(this.timer)clearInterval(this.timer);if(this.auto)clearInterval(this.auto);this.timer=null;this.auto=null;this.dir='none'}
 reset(){const o={targetCount:this.frame.target_count,targetSets:this.frame.target_sets,frameRateHz:1000/this.intervalMs,targetAngleDeg:this.frame.target_angle_deg,validAngleDeg:this.frame.valid_angle_deg,returnAngleDeg:this.frame.return_angle_deg,restDurationSec:this.restDurationSec};this.stop();Object.assign(this,new MoleFakeDataSource(o))}
 subscribe(l:(f:SquatMotionFrame)=>void){this.listeners.add(l);return()=>this.listeners.delete(l)}
 setSquatDirection(d:'down'|'up'|'none'){this.dir=d}
 setPaused(p:boolean){if(p&&this.frame.training_state==='RUNNING'){this.frame.training_state='PAUSED';this.dir='none'}else if(!p&&this.frame.training_state==='PAUSED')this.frame.training_state='RUNNING'}
 simulateCompleteCycle(){if(this.auto||this.frame.training_state!=='RUNNING')return false;let returning=false;this.dir='down';this.auto=setInterval(()=>{if(!returning&&this.frame.motion_progress>=.95){returning=true;this.dir='up'}if(returning&&this.frame.motion_progress<=.03){this.dir='none';if(this.auto)clearInterval(this.auto);this.auto=null}},this.intervalMs);return true}
 finishTraining(r:'FINISHED'|'STOPPED'){this.frame.training_state=r;this.dir='none'}
 private tick(){const started=this.frame.training_state;if(started==='RUNNING')this.running();else if(started==='REST')this.rest();else{this.frame.rep_event='none';this.frame.left_speed_deg_s=0;this.frame.right_speed_deg_s=0}this.frame.seq++;this.frame.timestamp_ms=Date.now()-this.startedAt;this.listeners.forEach(l=>l({...this.frame}));const a=this.after;this.after=null;if(a==='REST')this.enterRest();else if(a==='FINISHED')this.frame.training_state='FINISHED';else if(started==='FINISHED'||started==='STOPPED')this.stop();this.frame.rep_event='none'}
 private running(){const prior=this.frame.left_angle_deg;const step=(this.dir==='down'?1:this.dir==='up'?-1:0)*2.5;const next=Math.min(110,Math.max(0,prior+step));this.frame.left_angle_deg=next;this.frame.right_angle_deg=Math.max(0,Math.min(110,next+(this.dir==='none'?0:Math.sin(this.frame.seq*.2)*1.2)));this.frame.left_speed_deg_s=(next-prior)*1000/this.intervalMs;this.frame.right_speed_deg_s=this.frame.left_speed_deg_s;this.frame.motion_progress=Math.min(1,Math.max(0,next/this.frame.target_angle_deg));this.frame.motion_stage=this.dir==='down'?(this.frame.motion_progress>.9?'BOTTOM':'DESCENDING'):this.dir==='up'?(this.frame.motion_progress<.08?'STANDING':'RISING'):(this.frame.motion_progress>.9?'BOTTOM':'STANDING');this.frame.symmetry_percent=Math.max(0,100-Math.abs(this.frame.left_angle_deg-this.frame.right_angle_deg)*3);this.frame.quality=this.frame.symmetry_percent<85?'ASYMMETRY':'GOOD';this.frame.warning=this.frame.symmetry_percent<85?'left_right_asymmetry':'none';this.extrema.min=Math.min(this.extrema.min,next);this.extrema.max=Math.max(this.extrema.max,next);this.frame.left_rom_deg=this.frame.right_rom_deg=this.extrema.max-this.extrema.min;this.frame.lr_rom_diff_deg=Math.abs(this.frame.left_rom_deg-this.frame.right_rom_deg);if(this.frame.motion_progress>=this.frame.valid_angle_deg/this.frame.target_angle_deg)this.armed=true;if(this.armed&&this.dir==='up'&&next<=this.frame.return_angle_deg){this.armed=false;this.frame.left_count=Math.min(this.frame.target_count,this.frame.left_count+1);this.frame.right_count=this.frame.left_count;this.frame.rep_event='both_rep_done';this.completion();if(this.frame.left_count>=this.frame.target_count)this.after=this.frame.set_index<this.frame.target_sets?'REST':'FINISHED'}}
 private completion(){this.frame.completion_percent=Math.floor(this.frame.left_count*100/this.frame.target_count);this.frame.overall_completion_percent=Math.floor(((this.frame.set_index-1)*this.frame.target_count+this.frame.left_count)*100/(this.frame.target_sets*this.frame.target_count))}
 private enterRest(){this.frame.training_state='REST';this.frame.rest_remaining_sec=this.restDurationSec;this.frame.quality='REST';this.frame.warning='resting';this.restAt=Date.now();this.dir='none'}
 private rest(){this.frame.rest_remaining_sec=Math.max(0,this.restDurationSec-Math.floor((Date.now()-this.restAt)/1000));if(this.frame.rest_remaining_sec===0){this.frame.set_index++;this.frame.training_state='RUNNING';this.frame.left_count=0;this.frame.right_count=0;this.frame.completion_percent=0;this.frame.left_angle_deg=this.frame.right_angle_deg=0;this.frame.motion_progress=0;this.frame.motion_stage='STANDING';this.extrema={min:0,max:0}}}
}
