import {MultiplayerClient} from '../../game-platform/multiplayer/client';import {clearMultiplayerSession,loadMultiplayerSession,saveMultiplayerSession} from '../../game-platform/runtime/multiplayer-session';import type {MultiplayerBootstrap,RoomSnapshot} from '../../game-platform/multiplayer/types';import type {MoleTrainingResult} from '../types/result'
export interface MoleMultiplayerResult{protocolVersion:1;gameId:'mole';roomCode:string;mode:'PK'|'COOP';localPlayerId:string;localTraining:MoleTrainingResult;room:RoomSnapshot;completedAtMs:number}
interface R{client:MultiplayerClient;active:boolean;local:MoleTrainingResult|null;emitter:((r:MoleMultiplayerResult)=>void)|null;published:boolean;persistUnsubscribe:(()=>void)|null}let rt:R|null=null
function persist(){if(!rt)return;const s=rt.client.exportRoomSession();if(s)saveMultiplayerSession('mole',{...rt.client.bootstrap,gameId:'mole'},s,rt.active)}
export function initializeMoleMultiplayer(b:MultiplayerBootstrap){clearMoleMultiplayer();const client=new MultiplayerClient({...b,gameId:'mole'});rt={client,active:false,local:null,emitter:null,published:false,persistUnsubscribe:null};rt.persistUnsubscribe=client.store.subscribe(()=>persist());client.connect();return client}
export function restoreMoleMultiplayer(){if(rt)return rt.client;const s=loadMultiplayerSession('mole');if(!s)return null;const c=new MultiplayerClient(s.bootstrap);c.restoreRoomSession(s.clientSession);rt={client:c,active:s.activeTraining,local:null,emitter:null,published:false,persistUnsubscribe:null};rt.persistUnsubscribe=c.store.subscribe(()=>persist());c.connect();return c}
export function getMoleMultiplayerClient(){return rt?.client??null};export function beginMoleMultiplayer(){if(!rt||!rt.client.store.getSnapshot())return false;rt.active=true;persist();return true};export function isMoleMultiplayer(){return!!rt?.active&&!!rt.client.store.getSnapshot()};export function setMoleLocalResult(r:MoleTrainingResult){if(rt){rt.local=r;publishIfReady()}};export function registerMoleMultiplayerEmitter(e:((r:MoleMultiplayerResult)=>void)|null){if(rt)rt.emitter=e;publishIfReady()}
function publishIfReady(){if(!rt||rt.published||!rt.local)return;const room=rt.client.store.getSnapshot();if(!room||room.status!=='FINISHED')return;rt.published=true;const r:MoleMultiplayerResult={protocolVersion:1,gameId:'mole',roomCode:room.roomCode,mode:room.mode,localPlayerId:rt.client.bootstrap.identity.playerId,localTraining:rt.local,room,completedAtMs:Date.now()};rt.emitter?.(r)}
export function leaveMoleRoom(){if(!rt)return false;const sent=rt.client.leaveRoom();rt.active=false;rt.local=null;rt.published=false;clearMultiplayerSession('mole');return sent};export function clearMoleMultiplayer(){if(rt){rt.persistUnsubscribe?.();rt.client.close()}rt=null;clearMultiplayerSession('mole')}
