import type { ClientRoomMessage,MultiplayerBootstrap,MultiplayerProgressEvent,RoomMode,RoomSnapshot,RoomTrainingConfig,ServerRoomMessage } from './types'
import { RoomStore } from './room-store'
type SocketTaskLike={send(options:{data:string;fail?:(error:unknown)=>void}):void;close(options?:{code?:number;reason?:string}):void;onOpen(listener:()=>void):void;onMessage(listener:(event:{data:string|ArrayBuffer})=>void):void;onClose(listener:()=>void):void;onError(listener:(error:unknown)=>void):void}
export type MultiplayerConnectionState='CONNECTING'|'CONNECTED'|'RECONNECTING'|'FAILED'|'CLOSED'
export type MultiplayerConnectionListener=(state:MultiplayerConnectionState)=>void
export interface MultiplayerRoomSession { roomCode:string; resumeToken:string; clientSeq:number; snapshot:RoomSnapshot }
export class MultiplayerClient{
  readonly store=new RoomStore();private socket:SocketTaskLike|null=null;private connected=false;private deliberateClose=false
  private heartbeatTimer:ReturnType<typeof setInterval>|null=null;private reconnectTimer:ReturnType<typeof setTimeout>|null=null;private reconnectStartedAtMs=0;private reconnectAttempt=0
  private requestCounter=0;private clientSeq=0;private serverOffsetMs=0;private roomCode='';private ignoredRoomCode='';private resumeToken=''
  private pendingEvents=new Map<string,ClientRoomMessage>();private errorListener:((message:string)=>void)|null=null
  private connectionState:MultiplayerConnectionState='CLOSED';private connectionListeners=new Set<MultiplayerConnectionListener>()
  constructor(readonly bootstrap:MultiplayerBootstrap){}
  connect():void{if(this.socket||this.connected)return;this.deliberateClose=false;this.setConnectionState(this.reconnectAttempt>0||this.reconnectStartedAtMs>0?'RECONNECTING':'CONNECTING');let task:SocketTaskLike;try{task=uni.connectSocket({url:this.bootstrap.wsEndpoint,complete:()=>{}}) as unknown as SocketTaskLike}catch{this.scheduleReconnect();return}this.socket=task;task.onOpen(()=>this.handleOpen(task));task.onMessage(e=>{if(this.socket===task)this.handleMessage(e.data)});task.onClose(()=>this.handleClose(task));task.onError(()=>this.handleSocketError(task))}
  onError(listener:((message:string)=>void)|null):void{this.errorListener=listener}
  getConnectionState():MultiplayerConnectionState{return this.connectionState}
  isConnected():boolean{return this.connected&&this.connectionState==='CONNECTED'}
  subscribeConnection(listener:MultiplayerConnectionListener):()=>void{this.connectionListeners.add(listener);listener(this.connectionState);return()=>this.connectionListeners.delete(listener)}
  retryConnection():void{if(this.isConnected())return;this.stopTimers();const stale=this.socket;this.socket=null;this.connected=false;stale?.close({code:1000,reason:'manual_retry'});this.deliberateClose=false;this.reconnectAttempt=0;this.reconnectStartedAtMs=0;this.connect()}
  serverNowMs():number{return Date.now()+this.serverOffsetMs}
  exportRoomSession():MultiplayerRoomSession|null{const snapshot=this.store.getSnapshot();if(!snapshot||!this.roomCode||!this.resumeToken)return null;return{roomCode:this.roomCode,resumeToken:this.resumeToken,clientSeq:this.clientSeq,snapshot}}
  restoreRoomSession(session:MultiplayerRoomSession):void{this.roomCode=session.roomCode;this.resumeToken=session.resumeToken;this.clientSeq=Math.max(0,session.clientSeq);this.store.setSnapshot(session.snapshot)}
  createRoom(mode:RoomMode,config:RoomTrainingConfig):boolean{return this.send({type:'create_room',requestId:this.requestId(),identity:this.bootstrap.identity,authToken:this.bootstrap.authToken,mode,config:{...config,gameId:config.gameId??this.bootstrap.gameId??'fruit'}})}
  joinRoom(roomCode:string,config:RoomTrainingConfig):boolean{const sent=this.send({type:'join_room',requestId:this.requestId(),identity:this.bootstrap.identity,authToken:this.bootstrap.authToken,roomCode,config:{...config,gameId:config.gameId??this.bootstrap.gameId??'fruit'}});if(sent){this.roomCode=roomCode;if(this.ignoredRoomCode===roomCode)this.ignoredRoomCode=''}return sent}
  setReady(ready:boolean):boolean{return this.sendRoomCommand({type:'set_ready',requestId:this.requestId(),roomCode:this.roomCode,playerId:this.bootstrap.identity.playerId,ready})}
  startRoom():boolean{return this.sendRoomCommand({type:'start_room',requestId:this.requestId(),roomCode:this.roomCode,playerId:this.bootstrap.identity.playerId})}
  endRoom():boolean{return this.sendRoomCommand({type:'end_room',requestId:this.requestId(),roomCode:this.roomCode,playerId:this.bootstrap.identity.playerId})}
  sendProgress(progress:Omit<MultiplayerProgressEvent,'eventId'|'clientSeq'>):void{const eventId=`${this.bootstrap.identity.playerId}-${Date.now().toString(36)}-${(this.clientSeq+1).toString(36)}`;const message:ClientRoomMessage={type:'progress',requestId:this.requestId(),roomCode:this.roomCode,playerId:this.bootstrap.identity.playerId,progress:{...progress,eventId,clientSeq:++this.clientSeq}};this.pendingEvents.set(eventId,message);this.send(message,true)}
  leaveRoom():boolean{const code=this.roomCode;const sent=!!code&&this.isConnected()?this.send({type:'leave_room',requestId:this.requestId(),roomCode:code,playerId:this.bootstrap.identity.playerId}):false;if(code)this.ignoredRoomCode=code;this.roomCode='';this.resumeToken='';this.pendingEvents.clear();this.store.clear();return sent}
  leave():void{this.leaveRoom();this.close()}
  close():void{this.deliberateClose=true;this.stopTimers();this.socket?.close({code:1000,reason:'client_close'});this.socket=null;this.connected=false;this.setConnectionState('CLOSED')}
  private handleOpen(task:SocketTaskLike):void{if(this.socket!==task)return;this.connected=true;this.reconnectAttempt=0;this.reconnectStartedAtMs=0;this.setConnectionState('CONNECTED');if(this.roomCode&&this.resumeToken){this.send({type:'resume_room',requestId:this.requestId(),roomCode:this.roomCode,playerId:this.bootstrap.identity.playerId,resumeToken:this.resumeToken,lastRoomSeq:this.store.getSnapshot()?.roomSeq??0});this.pendingEvents.forEach(m=>this.send(m))}if(this.heartbeatTimer)clearInterval(this.heartbeatTimer);this.heartbeatTimer=setInterval(()=>this.send({type:'heartbeat',requestId:this.requestId(),roomCode:this.roomCode||undefined,playerId:this.bootstrap.identity.playerId,clientTimeMs:Date.now()}),5000)}
  private handleMessage(raw:string|ArrayBuffer):void{try{const text=typeof raw==='string'?raw:decodeUtf8(raw);const message=JSON.parse(text) as ServerRoomMessage;if(message.type==='room_snapshot'){if(message.snapshot.roomCode===this.ignoredRoomCode)return;this.roomCode=message.snapshot.roomCode;if(message.resumeToken)this.resumeToken=message.resumeToken;this.store.setSnapshot(message.snapshot)}else if(message.type==='ack'&&message.eventId)this.pendingEvents.delete(message.eventId);else if(message.type==='connected')this.serverOffsetMs=message.serverTimeMs-Date.now();else if(message.type==='pong')this.serverOffsetMs=message.serverTimeMs-(message.clientTimeMs+Date.now())/2;else if(message.type==='error')this.errorListener?.(message.message)}catch{this.errorListener?.('收到无法识别的房间数据')}}
  private handleSocketError(task:SocketTaskLike):void{if(this.socket!==task)return;this.socket=null;this.connected=false;task.close({code:1000,reason:'connection_error'});this.scheduleReconnect()}
  private handleClose(task:SocketTaskLike):void{if(this.socket!==task)return;this.socket=null;this.connected=false;if(this.heartbeatTimer)clearInterval(this.heartbeatTimer);this.heartbeatTimer=null;this.scheduleReconnect()}
  private scheduleReconnect():void{if(this.deliberateClose){this.setConnectionState('CLOSED');return}if(this.roomCode){if(!this.reconnectStartedAtMs)this.reconnectStartedAtMs=Date.now();if(Date.now()-this.reconnectStartedAtMs>=15000){this.setConnectionState('FAILED');this.errorListener?.('重连超过15秒，可选择继续单人训练或结束');return}}else if(this.reconnectAttempt>=3){this.setConnectionState('FAILED');this.errorListener?.('多人服务连接失败，请点击重新连接');return}const delay=Math.min(4000,500*(2**this.reconnectAttempt++));this.setConnectionState('RECONNECTING');this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;this.connect()},delay)}
  private sendRoomCommand(message:ClientRoomMessage):boolean{if(!this.roomCode){this.errorListener?.('尚未加入房间');return false}return this.send(message)}
  private send(message:ClientRoomMessage,silentWhenOffline=false):boolean{if(!this.isConnected()||!this.socket){if(!silentWhenOffline&&message.type!=='heartbeat')this.errorListener?.('多人服务尚未连接');return false}this.socket.send({data:JSON.stringify(message),fail:()=>this.errorListener?.('房间消息发送失败')});return true}
  private requestId():string{return`${this.bootstrap.identity.playerId}-${Date.now().toString(36)}-${(++this.requestCounter).toString(36)}`}
  private stopTimers():void{if(this.heartbeatTimer)clearInterval(this.heartbeatTimer);if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.heartbeatTimer=null;this.reconnectTimer=null}
  private setConnectionState(state:MultiplayerConnectionState):void{if(this.connectionState===state)return;this.connectionState=state;this.connectionListeners.forEach(l=>l(state))}
}
function decodeUtf8(buffer:ArrayBuffer):string{const bytes=new Uint8Array(buffer);let output='';for(let i=0;i<bytes.length;){const first=bytes[i++];if(first<0x80){output+=String.fromCharCode(first);continue}if(first<0xe0){const second=bytes[i++]??0;output+=String.fromCharCode(((first&0x1f)<<6)|(second&0x3f));continue}if(first<0xf0){const second=bytes[i++]??0,third=bytes[i++]??0;output+=String.fromCharCode(((first&0x0f)<<12)|((second&0x3f)<<6)|(third&0x3f));continue}const second=bytes[i++]??0,third=bytes[i++]??0,fourth=bytes[i++]??0,code=((first&7)<<18)|((second&0x3f)<<12)|((third&0x3f)<<6)|(fourth&0x3f),adjusted=code-0x10000;output+=String.fromCharCode(0xd800+(adjusted>>10),0xdc00+(adjusted&0x3ff))}return output}
