[platformio]
default_envs = BOARD_VIEWE_UEDX80480070E_WB_A

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
    platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
monitor_speed = 115200
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/lvgl.git#v8.4.0
    greiman/SdFat @ ^2.3.1

[common]
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I src

[rgb_mipi_lcd]
build_flags =
    -DLV_COLOR_16_SWAP=0

[env:BOARD_VIEWE_UEDX80480070E_WB_A]
build_flags =
    ${common.build_flags}
    ${rgb_mipi_lcd.build_flags}
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_VIEWE_UEDX80480070E_WB_A
    -DARDUINO_USB_CDC_ON_BOOT=0
board = BOARD_VIEWE_UEDX80480070E_WB_A
